services:
  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: jaeger

    ports:
      - "16686:16686"  # Web UI
      - "14268:14268"  # HTTP Collector
      - "4317:4317"    # OpenTelemetry gRPC
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true

  service-a:
    build:
      context: .
      dockerfile: service-a.DockerFile
    container_name: service-a
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
